# Modified from example at http://conda.pydata.org/docs/travis.html

language: python
sudo: false  # Use container-based infrastructure

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - "wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;"
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda env create -n gsee --file requirements.yml --file requirements_test.yml python=$TRAVIS_PYTHON_VERSION
  - source activate gsee
  - pip install --no-cache-dir .

script:
  - py.test --cov gsee --cov-report term-missing

after_success:
  - coveralls
