name: gsee

channels:
    - conda-forge

dependencies:
    - basemap >= 1.1.0
    - Cython >= 0.28.5
    - joblib >= 0.12
    - numpy >= 1.15.0
    - pandas >= 0.23.4
    - pyephem >= 3.7.6.0
    - scipy >= 1.1.0
    - seaborn >= 0.9.0
    - xarray >= 0.10.9
