name: gsee

channels:
    - conda-forge

dependencies:
    - Cython >= 0.27.3
    - joblib >= 0.11
    - numpy >= 1.10.1
    - pandas >= 0.18.0
    - pyephem >= 3.7.6.0
    - scipy >= 0.19.1
    - seaborn >= 0.9.0
    - xarray >= 0.10.7
